version: '3.8'
services:
  database-mysql:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - '3306:3306'
    # expose:
    #   - 3306

  backend:
    build:
      context: ../../Backend-NodeJS-Quickstart
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      # - DB_PORT=3306
      # - DB_HOST=database-mysql
      - DB_HOST=host.docker.internal
    ports:
      - 8080:8080
